"""Complete interactive parser method signatures left unannotated upstream."""

from collections.abc import Iterator

from lark.lexer import LexerThread, Token
from lark.parsers.lalr_parser_state import ParserState

class InteractiveParser:
    parser_state: ParserState[int]
    lexer_thread: LexerThread
    def copy(self, deepcopy_values: bool = True) -> InteractiveParser: ...
    def accepts(self) -> set[str]: ...
    def iter_parse(self) -> Iterator[Token]: ...
    def exhaust_lexer(self) -> list[Token]: ...
    def feed_token(self, token: Token) -> object: ...
    def feed_eof(self, last_token: Token | None = None) -> object: ...
    def resume_parse(self) -> object: ...
